### ISSUE TITLE
I can not convert more than one mnemonics per request

### ISSUE THREAD

**Issue by Sabesm** [dan-da/hd-wallet-derive#11]
I use the code in Ubuntu to convert the mnemonic to the address, but I can not convert more than one mnemonics per request. And even when I write --mnemonic = 111.txt, 10 mnemonics are already written in the file, but as a result I get addresses of only the first mnemonic, the remaining 9 seem to be not visible. Help me with this, how to import many mnemonic phrases into the query and get addresses from them for one request..

**Comment by dan-da** [comment]
Only one mnemonic is supported per execution.  Supporting multiple would be a big code change.   If you need more at this time, you can write an external script to exec hd-wallet-derive once for each mnemonic.
