### ISSUE TITLE
Please add missing path for Megacoin (MEC) and BitCloud (BTDX)

### ISSUE THREAD

**Issue by dalijolijo** [dan-da/hd-wallet-derive#12]
Added Megacoin as HD 217 and BitCloud as HD 218 here [satoshilabs/slips#368](https://github.com/satoshilabs/slips/pull/368)

**Comment by dan-da** [comment]
I see you have submitted a pull request for these here https://github.com/dan-da/coinparams/pull/3.   I will review it a bit later and if all is well, I can make a new release.

**Comment by dan-da** [comment]
done in https://github.com/dan-da/hd-wallet-derive/releases/tag/v0.4.2
