### ISSUE TITLE
Ethereum Private Key

### ISSUE THREAD

**Issue by tulang3587** [dan-da/hd-wallet-derive#14]
Hello, how can I get the 0x... formatted private key for Ethereum using this? I have no idea how to convert the obtained private key for use in MEW. I've already checked using https://iancoleman.io/bip39/ and the generated addresses is the same.

Here's what I've tried:

    $ ./hd-wallet-derive.php -g --coin=ETH --gen-key --format=jsonpretty
    [
        {
            "coin": "ETH",
            "seed": "09ab2535012579f73241a423d8c60fa85ef183d3cf3177458e659b4e2ba3c24bf8f6c3f9579610f8955c3fb1d330f85eaca65cf20be783c10d5b32e7710caf0f",
            "mnemonic": "deer limit raven sister scan assist hub giant fall liquid model ozone bone pigeon find odor rather grid pitch dish phrase youth leave warfare cause spot envelope magnet dumb shrug like emerge drip rain wide major thing devote august exhibit wild civil embody gate light large leader lecture",
            "root-key": "xprv9s21ZrQH143K3CDYhfReDg8N2XSPzgJ3pQqmK3bcB4aMEC3MAR4q5hxMcy6CgXS9Z6fsnvwJWZ5Cc9qvip9i9ZPjpt9VvoHwLEuuq2tUThK",
            "path": "m\/44'\/60'\/0'\/0",
            "xprv": "xprv9zfJzhL9QYqpBE1nq11Ju8XfigwKDGX2Z3Vpw8k9rnnv2yCf2nLMseZ3h2mfSLhoHSGjSvqQ5ZZvyoR7DxxbbDG6jeqkBZEF4RkBNGv77zi",
            "xpub": "xpub6DefQCs3EvQ7Pi6Fw2YKGGUQGimocjEsvGRRjX9mR8KtumXoaKecRSsXYHKKg5pErJcUPgNujXLYwNMo6jhSWWuETBfadwjqdB6KWYAw9Cy",
            "comment": null
        }
    ]

Generated address from the xpriv:

    $ ./hd-wallet-derive.php --coin=ETH -g --key=xprv9s21ZrQH143K3CDYhfReDg8N2XSPzgJ3pQqmK3bcB4aMEC3MAR4q5hxMcy6CgXS9Z6fsnvwJWZ5Cc9qvip9i9ZPjpt9VvoHwLEuuq2tUThK --format=jsonpretty --numderive=1 --path='m/0'
    [
        {
            "path": "m\/0\/0",
            "address": "0xD96bA7A4c4b9c49f041Fd2F677C341475b5e6477",
            "xprv": "xprv9w3iV1wGQfMrdyfBTju3jqyuoBxafVpPmSJ84cdafueyzgoiP48CZyZ4uLE5fvNF3Fk5UFjQQoQEGzuSztQR44eCT3WwiKCrHP5PaniMWME",
            "xpub": "xpub6A34tXUAF2v9rTjeZmS46yveMDo54xYF8fDis13CEFBxsV8rvbST7msYkbzwbtR8HrjUX4ygd83HWDChGjCqeWLDoVbAhW9qTzZp86HoNL6",
            "privkey": "15BZH1BFgppf55JefynKSGg9FR17ssGoaRe5sVnVbZosGJXWrPQE",
            "pubkey": "02dea1c1dbad6f37e3eb88c2ea5a37f6d822f716496463cf7db867bb3ea768493a",
            "pubkeyhash": "7bd6091eca842a4e3d7a7d33485582305b65f01b",
            "index": 0
        }
    ]

And here's the result from the BIP39 site:

    path,address,public key,private key
    m/0/0,0xD96bA7A4c4b9c49f041Fd2F677C341475b5e6477,0x02dea1c1dbad6f37e3eb88c2ea5a37f6d822f716496463cf7db867bb3ea768493a,0x7cc7bdd192e58e02c54de5450524d8cb9c37af26ed400c5d6150d3256149410d

The addresses are the same `0xD96bA7A4c4b9c49f041Fd2F677C341475b5e6477`, but how do I convert that private key `15BZH1BFgppf55JefynKSGg9FR17ssGoaRe5sVnVbZosGJXWrPQE` to `0x7cc7bdd192e58e02c54de5450524d8cb9c37af26ed400c5d6150d3256149410d`?

Thanks in advance.

**Comment by dan-da** [comment]
Thx for the detailed description.    The private key is a number that is being printed (serialized) in Bitcoin's WIF format.

Ethereum standard is to display private keys using hex serialization.

To convert from Wif to Hex, one first needs to decode the Wif value into an integer number and then into hex.

That said, in commit f3bab5debba4c3d80cfbfec6985dc98c5e415a13 I just modified the code so it will print hex values for ethereum private keys.  That should solve your issue.   Please give it a try and let me know...

**Comment by tulang3587** [comment]
Thank you, it works perfectly now.
