### ISSUE TITLE
derive bip44 hardened addresses from xpub key

### ISSUE THREAD

**Issue by zhangrui231** [dan-da/hd-wallet-derive#15]
I run into problems when deriving addresses from xpub keys with hardened indexes.
```
$ ./hd-wallet-derive.php --key=tpubD6NzVbkrYhZ4YNH7DUU9F952c1CirWc9TxUubQVnAXmjRjWUqDwraCMJoZxC5Az9agrjnKUrhSwnHtbcGuQ7SfUqWigegxYgt3YS12nimZM --path="m/44'/1'/0'/0/x" --coin=btc-test --cols=path,address -g
2018-11-22T03:07:38+00:00 [pid: 12140] [exception] -- #1: Exception. code: 0. Can't derive a hardened key without the private key
```
how does one generate the seed in a cold offline environment and then derive keys from that chain without exposing the seed in an online ?I must be misunderstanding something...

**Comment by dan-da** [comment]
For deriving from hardened path you need to provide a master private key (xprv).

Technically speaking, the xprv is only needed for the hardened portion of the path, then an xpub could be used for the non-hardened portion, but hd-wallet-derive does not presently support that.

more background:

- https://bitcoin.stackexchange.com/questions/68740/generate-hd-addresses-using-publickey-bip44/68745#68745
- https://github.com/Bit-Wasp/bitcoin-php/issues/582
