### ISSUE TITLE
in bip39 the mnemonic length is 12-24 but I get 48 words

### ISSUE THREAD

**Issue by qianchong88** [dan-da/hd-wallet-derive#16]
I use the /hd-wallet-derive.php  --gen-key --format=jsonpretty -g command to generate mnemonic words, get 48 mnemonic words.but in bip39 the mnmonic length is 12-24 .is there somthing wrong or somthing i misunderstood?

**Comment by dan-da** [comment]
Thanks for bringing this to my attention.  Apparently I forgot to add a command-line switch for setting it.  I will do that asap.

For right now, if you need 12 or 24 words, you can modify the following line in src/WalletDerive.php:

> $entropy = $random->bytes(64)

Change the 64 to:

- 16 for 12 words.
- 32 for 24 words.

**Comment by qianchong88** [comment]
many thanks!

**Comment by dan-da** [comment]
fixed in ca691ba209fdd7688f6d922e6585737a85170aad
