### ISSUE TITLE
while executing.. having error

### ISSUE THREAD

**Issue by tysonchamp** [dan-da/hd-wallet-derive#2]
here is the command:

./hd-wallet-derive.php --mnemonic="record message trigger first style lottery fly notable tackle twelve peace learn" --path="m/44'/0'/0'/0" -g --includeroot --numderive=2 --cols=path,address,privkey,pubkey,xprv

**error below:**

Uncaught Exception. code: 0, message: Call to undefined method BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PublicKey::getAddress()
/home/tyson/Downloads/hd-wallet-derive-master/lib/wallet_derive.class.php : 56

Stack Trace:
#0 /home/tyson/Downloads/hd-wallet-derive-master/hd-wallet-derive.php(38): wallet_derive->derive_keys('xprv9s21ZrQH143...')
#1 /home/tyson/Downloads/hd-wallet-derive-master/hd-wallet-derive.php(20): main(Array)
#2 {main}

WARNING: strictmode\ALERTS_MAILTO not defined in config.  To disable this warning, define 'strictmode\ALERTS_DISABLE'.  alert not sent with subject: [tyson-Lenovo-G50-80] [hd-wallet-derive.php] Uncaught exception! [pid: 10687]

Now exiting.  Please report this problem to the software author

**Comment by dan-da** [comment]
thx for the report.

first guess.... It could be that the version of bitwasp you are using is incompatible.  They might have made a breaking API change.    You could try using = instead of > in composer.json, then run compose update.

**Comment by tysonchamp** [comment]
added this line "mdanter/ecc": "=0.3.0", and reinstalled the libraries.. then here below is the error

tyson@tyson-Lenovo-G50-80:~/Downloads/hd-wallet-derive-master$ ./hd-wallet-derive.php --mnemonic="refuse brush romance together undo document tortoise life equal trash sun ask" --path="m/44'/0'/0'/0" -g --includeroot --numderive=2 --cols=path,address,privkey,pubkey,xprv
2018-03-30T22:25:17+05:30 [pid: 8081] [exception] -- #1: ErrorException. code: 2. gmp_div(): Unable to convert variable to GMP - string is not an integer

/home/tyson/Downloads/hd-wallet-derive-master/vendor/mdanter/ecc/src/Math/Gmp.php : 89

Stack Trace:
#0 [internal function]: strictmode\_global_error_handler(2, 'gmp_div(): Unab...', '/home/tyson/Dow...', 89, Array)
#1 /home/tyson/Downloads/hd-wallet-derive-master/vendor/mdanter/ecc/src/Math/Gmp.php(89): gmp_div('m', Object(GMP))
#2 /home/tyson/Downloads/hd-wallet-derive-master/vendor/bitwasp/bitcoin/src/Math/BinaryMath.php(38): Mdanter\Ecc\Math\Gmp->rightShift('m', '31')
#3 /home/tyson/Downloads/hd-wallet-derive-master/vendor/bitwasp/bitcoin/src/Key/Deterministic/HierarchicalKey.php(198): BitWasp\Bitcoin\Math\BinaryMath->isNegative('m', 32)
#4 /home/tyson/Downloads/hd-wallet-derive-master/vendor/bitwasp/bitcoin/src/Key/Deterministic/HierarchicalKey.php(226): BitWasp\Bitcoin\Key\Deterministic\HierarchicalKey->getHmacSeed('m')
#5 /home/tyson/Downloads/hd-wallet-derive-master/vendor/bitwasp/bitcoin/src/Key/Deterministic/HierarchicalKey.php(257): BitWasp\Bitcoin\Key\Deterministic\HierarchicalKey->deriveChild('m')
#6 /home/tyson/Downloads/hd-wallet-derive-master/vendor/bitwasp/bitcoin/src/Key/Deterministic/HierarchicalKey.php(273): BitWasp\Bitcoin\Key\Deterministic\HierarchicalKey->deriveFromList(Array)
#7 /home/tyson/Downloads/hd-wallet-derive-master/lib/wallet_derive.class.php(80): BitWasp\Bitcoin\Key\Deterministic\HierarchicalKey->derivePath('m/44'/0'/0'/0/0')
#8 /home/tyson/Downloads/hd-wallet-derive-master/hd-wallet-derive.php(38): wallet_derive->derive_keys('xprv9s21ZrQH143...')
#9 /home/tyson/Downloads/hd-wallet-derive-master/hd-wallet-derive.php(20): main(Array)
#10 {main}

gmp_div(): Unable to convert variable to GMP - string is not an integer

**Comment by dan-da** [comment]
Fixed in 5b54025166bff22051e73eaf95718ed2a658aebe
