### ISSUE TITLE
request: deriving keys for x accounts instead of x addresses

### ISSUE THREAD

**Issue by twfink** [dan-da/hd-wallet-derive#20]
Thanks for this great tool. This suggestion would save Ledger users some time and effort

https://github.com/MyCryptoHQ/MyCrypto/issues/2070
>in Ledger Live instead, the idea is to follow BIP44, which means the first address is derived on m/44'/60'/0'/0/0, the second on m/44'/60'/1'/0/0, and so on,.. so in other words using the account field of BIP44. (m/44'/60'/x'/0/0)

https://github.com/LedgerHQ/ledger-live-desktop/issues/1185
> Ledger Live uses m/44'/60'/x'/0/0 for addresses, but Trezor and MEW use m/44'/60'/0'/0/x, which also seems to be the consensus that has been reached on EIP 84. This will lead to the same derivation for the first address, but different derivations for subsequent addresses.

Currently, Ledger users have to execute the command for each account with the path fully specified.

**Comment by dan-da** [comment]
Thx for the ledger path info.

I think that the way to do this right would be to introduce a concept of path templates.  So hd-wallet-derive would have a list of templates for various wallet software.  I've considered doing this previously, but I figured I'd wait for a request.   :-)

I will see about adding path template code when I get some free time.   If anyone can point me towards an accurate/current and hopefully maintained list of bip32 paths used by various wallet software, that would be super helpful.

**Comment by twfink** [comment]
Glad to know you already have that in mind.  

This is what I was able to find for Trezor, but unfortunately, it's not a comprehensive list:
https://github.com/trezor/trezor-core/blob/118ca37304e5ea78f1e7da8ca0d1701cfd53cefa/docs/coins/README.md

maybe @prusnak could help?

**Comment by dan-da** [comment]
> Ledger Live uses **m/44'/60'/x'/0/0** for addresses, but Trezor and MEW use m/44'/60'/0'/0/x

Oh, I just spotted this.  Interesting.   x is in the middle of the path, not the end.  So supporting ledger-live is more than just a path preset, it is actually about iterating elsewhere, which requires a change to the core derivation code, path verification, etc.  I'll have to take a look if there are any gotchas preventing it.

**Comment by twfink** [comment]
Yes I tried to place it in the middle but got an error. Ledger says they made this decision for privacy reasons.

**Comment by dan-da** [comment]
@twfink I just added support for using x or x' in the middle of a path.   (algo change in a202759012dfe28711adecfcd4296b2797821a2a)

If you have a chance please give master a try with ledger live and let me know it works or if any issues.

**Comment by twfink** [comment]
Thank you! I'll test once my new Ledger arrives in about tweeks.

**Comment by dan-da** [comment]
Implemented path presets (with 26 presets defined) in df220b5bb84811b489b24a03021b3ed685ad8a01.   Closing this.
