### ISSUE TITLE
preset is ignored when mnemonic is provided

### ISSUE THREAD

**Issue by twfink** [dan-da/hd-wallet-derive#22]
tested for "ledgerlive"

**Comment by dan-da** [comment]
nice catch, thx.    fixed in 2455ee1a83be350fbfc456dc2877e25e55382bc2.   Can you test please?

**Comment by twfink** [comment]
thanks for the quick response.

the preset works withe mnemonic now but I believe it should be changed from:
>m/44'/c'/x'/y/0'
to:
>m/44'/c'/x'/y/0

**Comment by dan-da** [comment]
whoops.  my mistake.  fixed in b659bd60a8939215a3ec3b15c13dfdf85438a6fe.    Please test, and after you confirm it generates correct addresses I will make a new release.

**Comment by twfink** [comment]
it's perfect now. thank you!
