### ISSUE TITLE
XMR

### ISSUE THREAD

**Issue by melaxon** [dan-da/hd-wallet-derive#27]
Do you eventually know how to make it to generate keys and addresses for Monero?
Currently it returns:

` 
$ php hd-wallet-derive.php -g --gen-key --coin=xmr

+---------+
|             0 |
+---------+
| No Data |
+---------+
`

**Comment by dan-da** [comment]
No, monero is very different and I'm not sure how to go about that.  I would happily accept a pull request if any monero dev wants to add that functionality.

I doubt the underlying bitcoin-php lib even has the required plumbing, so it would be a faily big change/effort.

**Comment by dan-da** [comment]
I started a new tool [subaddress-derive-xmr](https://github.com/dan-da/subaddress-derive-xmr). 

@melaxon if you are able, please test it out by comparing generated subaddresses to monero-cli and let me know your results.  I don't presently have monero software installed, so it is totally untested.

closing Any further xmr issues can be opened in the other repo.

**Comment by melaxon** [comment]
Hello!
Great news! I sure will try your tool but not right now, I also do not currently have anything for monero but need it badly


>Пятница, 27 сентября 2019, 22:20 +03:00 от dan-da <notifications@github.com>:
>
>I started a new tool  subaddress-derive-xmr .
>@melaxon if you are able, please test it out by comparing generated subaddresses to monero-cli and let me know your results.  I don't presently have monero software installed, so it is totally untested.
>closing Any further xmr issues can be opened in the other repo.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
ilib@mail.ru
