### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by melaxon** [dan-da/hd-wallet-derive#30]
Did you try this package with php 7.2 or newer?
I continuously receive "Illegal instruction: 4"
Any idea?

`
$ php hd-wallet-derive.php -g --key=xpub661MyMwAqRbcFKnmbAh17DGKL5gECTihoXw1udpxtSPrgurw5reZoqVLMCRqnbubYrpfPYbemmkxuHTnKfAemaanGKSNAjwaj5k2ZmB84FP

Illegal instruction: 4
`

**Comment by dan-da** [comment]
hmm, that's strange.  It works fine here with php 7.2.22 running the exact command you posted.

I would guess you may have an issue with your PHP installation.  See for example:
https://github.com/composer/composer/issues/6494

**Comment by dan-da** [comment]
closing.   Feel free to re-open if you can reproduce with a fresh PHP install.  In that case, please include OS version, PHP version and output of phpinfo().
