### ISSUE TITLE
how can i get Account Extended Public Key from seed (mnemonic)

### ISSUE THREAD

**Issue by anajo333** [dan-da/hd-wallet-derive#35]
**i tryed too much to get Account Extended Public Key (xpub) from seed (mnemonic)**
like this site [iancoleman](https://iancoleman.io/bip39/)

but i get only BIP32 Extended Public Key
**for example :** 
i will use this seed "trip tongue legend magic olive size flame juice company spatial shadow sleep"

> php hd-wallet-derive.php --mnemonic="trip tongue legend magic olive size flame juice company spatial shadow sleep" --cols=xpub -g --format=jsonpretty --numderive=1 --includeroot --path="m/44'/0'/0'"

```
[
    {
        "xpub": "xpub661MyMwAqRbcFmYtf6S4BQjjDyPx7nEJd24uzZeu89znTK9hn1fEYDgo8YnE4KypNsj7oxMnz3KhuwThmxwW8KxoQipXXRoS2N3xJunjVpK"
    },
    {
        "xpub": "xpub6EdvtDRjwusAM5aSMrTnYnjoyEdPWHNzjqbjkMA3FS2SYN5iXdt4rAaL878s3y3yrnVJ3jFeSMj75Ank7vh2aUVAaz6JpgFw2QZDFWxPopC"
    }
]
```

**but in site :**

![image](https://user-images.githubusercontent.com/37766035/80644742-70b07380-8a6a-11ea-8f55-7a47be278e55.png)

i want to get **Account Extended Public Key** not _BIP32 Extended Public Key_
How can i do that Please Answer soon as possible

Thank you ❤️

**Comment by dan-da** [comment]
Try this:

```
$ php hd-wallet-derive.php --mnemonic="trip tongue legend magic olive size flame juice company spatial shadow sleep" --cols=xpub -g --format=jsonpretty --numderive=1  --path="m/44'/0'/x'"

{
    "xpub": "xpub6CJ4E934TPwDmDvnEgcSp6mFDQeoTuXHShfFnAprrtJRPSLHZpxRuJr3gCgLSoGVxahiqkRXmuCY41CkJx2cHYx4ZN91UYqCs6P1EQiXcvq"
}
```

That matches the key produced by iancoleman's site, for me.

For the Bip44 Account extended public key, we want to derive the first hardened key under m/44'/0'.  The trick in hd-wallet-derive is to use x', which tells the tool to derive a series of hardened keys, rather then the default non-hardened keys.

**Comment by anajo333** [comment]
> Try this:
> 
> ```
> $ php hd-wallet-derive.php --mnemonic="trip tongue legend magic olive size flame juice company spatial shadow sleep" --cols=xpub -g --format=jsonpretty --numderive=1  --path="m/44'/0'/x'"
> 
> {
>     "xpub": "xpub6CJ4E934TPwDmDvnEgcSp6mFDQeoTuXHShfFnAprrtJRPSLHZpxRuJr3gCgLSoGVxahiqkRXmuCY41CkJx2cHYx4ZN91UYqCs6P1EQiXcvq"
> }
> ```
> 
> That matches the key produced by iancoleman's site, for me.
> 
> For the Bip44 Account extended public key, we want to derive the first hardened key under m/44'/0'. The trick in hd-wallet-derive is to use x', which tells the tool to derive a series of hardened keys, rather then the default non-hardened keys.

**thank you bro 
can we talk on telegram or any IM app ? 
my telegram : @mxs1010
and Thank you again ❤️**
