### ISSUE TITLE
Problem installing hd-wallet-derive

### ISSUE THREAD

**Issue by iDataist** [dan-da/hd-wallet-derive#39]
I'm using Windows 10 Pro and installing hd-wallet-derive using the command below. 
```
git clone https://github.com/dan-da/hd-wallet-derive
cd hd-wallet-derive
php -r "readfile('https://getcomposer.org/installer');" | php
php -d pcre.jit=0 composer.phar install
```
The installation was not successful. I wonder if anyone has encountered something similar previously. Any insights on how to fix it would be greatly appreciated. 
![Capture](https://user-images.githubusercontent.com/46846986/92419651-6bf47e00-f134-11ea-85ca-6dee9d7d4ff7.PNG)

**Comment by iDataist** [comment]
I solved this issue by using the command prompt instead of git bash

**Comment by dan-da** [comment]
thx for the report.   I've never actually tried to install on windows, so I'm glad you were able to make it work.

a couple thoughts:

1. Any method of installing composer should be fine.  See getcomposer.org for details.
2. the 'stdout is not a tty' error is weird.  You would probably have better results with cygwin or even wsl than git bash.
