### ISSUE TITLE
Error during ”composer install”

### ISSUE THREAD

**Issue by mocapapa** [dan-da/hd-wallet-derive#49]
I found a following error.

> $ php composer.phar install
> All settings correct for using Composer
> Downloading...
> Composer (version 2.5.1) successfully installed to: /media/sf_/hd-wallet-derive/composer.phar
> Use it: php composer.phar
> No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
> Loading composer repositories with package information
> Info from https://repo.packagist.org: #StandWithUkraine
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
>   Problem 1
>     - **lastguest/murmurhash 2.0.0 requires php ^7** -> your php version (8.1.13) does not satisfy that requirement.
>     - bitwasp/bitcoin dev-master requires lastguest/murmurhash v2.0.0 -> satisfiable by lastguest/murmurhash[2.0.0].
>     - Root composer.json requires bitwasp/bitcoin dev-master#8782bc6c470e342d4e0cb67eb036974f133b950b -> satisfiable by bitwasp/bitcoin[dev-master].

I think bitwasp/bitcoin requires **murmurhash v2.0.0**, while murmurhash v2.1.1 (the latest one) requires php v8.x. I don't know how to fix bitwasp/bitcoin's composer.json.

**Comment by dan-da** [comment]
This is fixed by #55.

Thx for the report.
