### ISSUE TITLE
Adding a currency that the library does not support

### ISSUE THREAD

**Issue by sara1512** [dan-da/hd-wallet-derive#56]
In the dan-da/hd-wallet-derive library, I want to add currency information to this library that is not supported by the dan-da/hd-wallet-derive library.

**Comment by dan-da** [comment]
The currency list and parameters are obtained from CoinParams.    Instructions for contributing new coins are here:
https://github.com/dan-da/coinparams?tab=readme-ov-file#contributions-welcome
