### ISSUE TITLE
col path contain always m/x - Derive addresses from xpub key

### ISSUE THREAD

**Issue by Telariust** [dan-da/hd-wallet-derive#8]
Keys on diff path(bip32/bip44/etc) generated correctly, but col "path" always contains val "m/x".
Simple question - can we recover full path from xpub/xprv? Its relative or def val cap code?
(some times need detect path algoritm derive from pkey)
...................
had seen, its really
dan-da/hd-wallet-addrs
--cols=relpath,abspath
...................
dan-da/hd-wallet-derive/README.md#how-address-derivation-works
ok, undestand, sry, close

**Comment by dan-da** [comment]
At present, path information is not encoded in xpub/xprv, so no it cannot be retrieved and path info must be externally supplied. [Slip-0032](https://github.com/satoshilabs/slips/blob/master/slip-0032.md) defines an alternate serialization that does include full path, but to my knowledge no wallets are using that presently.
